version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.4
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    volumes:
      - ./realm-config.json:/opt/keycloak/data/import/realm-config.json:ro
    command:
      - start-dev
      - --import-realm